all:
  hosts:
    inetRouter:
      ansible_host: 127.0.0.1
      ansible_port: 30022
      ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ansible_host: 127.0.0.1
      ansible_port: 31022
      ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
    centralServer: 
      ansible_host: 127.0.0.1
      ansible_port: 32022
      ansible_private_key_file: .vagrant/machines/centralServer/virtualbox/private_key
    inetRouter2:
      ansible_host: 127.0.0.1
      ansible_port: 33022
      ansible_private_key_file: .vagrant/machines/inetRouter2/virtualbox/private_key
