all:
  hosts:
    inetRouter:
      ansible_host: 192.168.18.1
      ansible_port: 30022
      ansible_user: vagrant
      ansible_password: vagrant
    centralRouter:
      ansible_host: 192.168.18.1
      ansible_port: 31022
      ansible_user: vagrant
      ansible_password: vagrant
    centralServer: 
      ansible_host: 192.168.18.1
      ansible_port: 32022
      ansible_user: vagrant
      ansible_password: vagrant
    inetRouter2:
      ansible_host: 192.168.18.1
      ansible_port: 33022
      ansible_user: vagrant
      ansible_password: vagrant
